workflows:
  build_apk_debug:
    name: Build Debug APK
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
      # No vars section needed - credentials come from environment variables
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor -v
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Clean and Build Debug APK
        script: |
          flutter clean
          flutter pub get 
          flutter build apk --debug --verbose --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  build_apk_release:
    name: Build Release APK
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor -v
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Clean and Build Release APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release --verbose --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  build_app_bundle:
    name: Build App Bundle
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor -v
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Clean and Build App Bundle
        script: |
          flutter clean
          flutter pub get
          flutter build appbundle --release --verbose --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab