workflows:
  build_apk_debug:
    name: Build Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Debug APK
        script: |
          flutter build apk --debug -v
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
