workflows:
  build_apk_debug:
    name: Build Debug APK
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor -v

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Clean and Build Debug APK with .env loaded
        script: |
          flutter clean
          flutter pub get
          
          # ✅ Load .env variables
          export $(grep -v '^#' .env | xargs)

          # ❌ Fail if missing required env vars
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "❌ ERROR: Missing required environment variables."
            exit 1
          fi

          echo "🔍 Environment variables check:"
          echo "SUPABASE_URL length: ${#SUPABASE_URL}"
          echo "SUPABASE_ANON_KEY length: ${#SUPABASE_ANON_KEY}"

          flutter build apk --debug \
            --split-per-abi \
            --tree-shake-icons \
            --verbose \
            --dart-define=SUPABASE_URL="$SUPABASE_URL" \
            --dart-define=SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY"

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk