workflows:
  build_apk_debug:
    name: Build Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor
      - name: Clean build
        script: |
          flutter clean
          flutter pub cache repair
          flutter pub get
          flutter analyze
      - name: Build Debug APK
        script: |
          flutter build apk --debug --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  build_apk_release:
    name: Build Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor
      - name: Clean build
        script: |
          flutter clean
          flutter pub get
      - name: Build Release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  build_app_bundle:
    name: Build App Bundle
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - google_play
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor
      - name: Clean build
        script: |
          flutter clean
          flutter pub get
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab