workflows:
  build_apk:
    name: Build APK with latest Flutter
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: true
    scripts:
      - name: Clean build
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk