name: khilonjiya_com
description: A comprehensive marketplace application built with Flutter for khilonjiya.com - আমাৰ সংস্কৃতি, আমাৰ গৌৰৱ (Our Culture, Our Pride)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # 🎯 STATE MANAGEMENT & ARCHITECTURE
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # 🎨 UI & RESPONSIVE DESIGN
  sizer: ^3.0.5
  flutter_screenutil: ^5.9.0
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0

  # 🌐 NETWORK & API
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9
  dio: ^5.4.3+1
  connectivity_plus: ^6.1.4
  retrofit: ^4.0.3
  internet_connection_checker: ^3.0.1
  postgrest: ^2.4.2

  # 💾 STORAGE & PERSISTENCE
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2

  # 🔐 AUTHENTICATION & SECURITY
  supabase_flutter: ^2.4.0
  google_sign_in: ^7.1.0
  flutter_facebook_auth: ^7.1.2
  local_auth: ^2.1.7
  crypto: ^3.0.3

  # 🖼️ IMAGES & MEDIA
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  photo_view: ^0.15.0
  flutter_image_compress: ^2.4.0
  video_player: ^2.8.2
  file_picker: ^10.2.0

  # 📍 LOCATION & MAPS
  google_maps_flutter: ^2.6.0
  location: ^8.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # 💰 PAYMENTS
  razorpay_flutter: ^1.3.6

  # 🔔 NOTIFICATIONS & MESSAGING
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0

  # 📱 DEVICE FEATURES
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  url_launcher: ^6.2.5

  # 📊 DATA VISUALIZATION & CHARTS
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39

  # 🔍 SEARCH & FILTERS
  flutter_typeahead: ^5.2.0  # ✅ Upgraded to fix dependency conflict

  # 📅 DATE & TIME
  table_calendar: ^3.1.1

  # 🎪 ONBOARDING & TUTORIALS
  introduction_screen: ^3.1.12

  # 🛠️ UTILITIES
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  uuid: ^4.3.3
  timeago: ^3.6.0
  mask_text_input_formatter: ^2.6.0

  # 🔗 DEEP LINKING & QR
  qr_flutter: ^4.1.0

  # 🌍 LOCALIZATION
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


  # 🏗️ CODE GENERATION
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  hive_generator: ^2.0.1
  retrofit_generator: ^9.7.0


  # 🧪 TESTING
  mockito: ^5.4.6
  bloc_test: ^10.0.0


  # 📱 APP CONFIGURATION
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700